# SPDX-License-Identifier: MIT

apiVersion: 1

deleteDatasources:
  - name: SQLite
    orgId: 1

datasources:
  - name: SQLite
    type: frser-sqlite-datasource
    access: proxy
    uid: flexric-sqlite
    url: ''
    isDefault: true
    editable: true
    jsonData:
      path: /xapp_db_dir/xapp_db
